const area=document.querySelector('#area');const total=document.querySelector('#total');const buttons=[...document.querySelectorAll('.toggle button')];let rate=69000;function calc(){if(!area||!total)return;const a=Math.max(0,Number(area.value)||0);total.textContent=new Intl.NumberFormat('ru-RU').format(a*rate)+' ₸'}if(area)area.addEventListener('input',calc);buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');rate=Number(b.dataset.rate);calc()}));calc();
const form=document.querySelector('#contactForm');if(form){form.addEventListener('submit',e=>{e.preventDefault();const name=form.elements.name.value.trim();const phone=form.elements.phone.value.trim();const areaValue=form.elements.area.value.trim();const text=`Здравствуйте! Хочу обсудить ремонт.\nИмя: ${name}\nТелефон: ${phone}\nПлощадь: ${areaValue||'не указана'} м²`;window.open('https://wa.me/77073749855?text='+encodeURIComponent(text),'_blank','noopener')})}
const burger=document.querySelector('.burger');const nav=document.querySelector('.nav nav');if(burger&&nav){burger.addEventListener('click',()=>{const open=nav.dataset.open==='1';nav.dataset.open=open?'0':'1';nav.style.display=open?'none':'flex';nav.style.position='absolute';nav.style.top='70px';nav.style.left='15px';nav.style.right='15px';nav.style.flexDirection='column';nav.style.gap='0';nav.style.padding='12px';nav.style.background='#171714';nav.style.border='1px solid rgba(255,255,255,.15)';nav.querySelectorAll('a').forEach(a=>{a.style.padding='12px';a.addEventListener('click',()=>{nav.style.display='none';nav.dataset.open='0'},{once:true})})})}
const cards=[...document.querySelectorAll('.work-card')],lightbox=document.querySelector('#lightbox'),lightboxImage=document.querySelector('#lightboxImage'),lightboxName=document.querySelector('#lightboxName');let currentWork=0,touchStartX=0;function showWork(i){if(!cards.length)return;currentWork=(i+cards.length)%cards.length;const img=cards[currentWork].querySelector('img');lightboxImage.src=img.src;lightboxImage.alt=img.alt;lightboxName.textContent=cards[currentWork].dataset.name||img.alt}function openWork(i){showWork(i);lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open')}function closeWork(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.classList.remove('lightbox-open')}cards.forEach((card,i)=>{card.setAttribute('tabindex','0');card.addEventListener('click',()=>openWork(i));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openWork(i)}})});if(lightbox){lightbox.querySelector('.lightbox-close').addEventListener('click',closeWork);lightbox.querySelector('.lightbox-prev').addEventListener('click',e=>{e.stopPropagation();showWork(currentWork-1)});lightbox.querySelector('.lightbox-next').addEventListener('click',e=>{e.stopPropagation();showWork(currentWork+1)});lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeWork()});lightbox.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX},{passive:true});lightbox.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>45)showWork(currentWork+(dx<0?1:-1))},{passive:true})}document.addEventListener('keydown',e=>{if(!lightbox||!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeWork();if(e.key==='ArrowLeft')showWork(currentWork-1);if(e.key==='ArrowRight')showWork(currentWork+1)});

// 3D project gallery
const service3d=[...document.querySelectorAll('.service-cards article')].find(card=>card.querySelector('h3')?.textContent.trim()==='3D-проектирование');
if(service3d){
 const link3d=service3d.querySelector('a');
 const projects3d=[['assets/кухня 3д.png','Кухня'],['assets/гостиная 3д.png','Гостиная'],['assets/санузел 3д.png','Санузел'],['assets/спальня 3д.png','Спальня']];
 service3d.classList.add('service-3d-featured');service3d.setAttribute('tabindex','0');service3d.setAttribute('role','button');service3d.setAttribute('aria-label','Открыть галерею 3D-проектов');
 const preview=document.createElement('div');preview.className='service3d-preview';preview.innerHTML='<img src="assets/кухня 3д.png" alt="Пример 3D-проекта кухни"><span>4 проекта · открыть галерею</span>';service3d.insertBefore(preview,service3d.querySelector('h3'));
 link3d.textContent='Смотреть 3D-проекты →';link3d.classList.add('service3d-cta');
 const modal=document.createElement('div');modal.className='project3d-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="project3d-panel"><button class="project3d-close" type="button" aria-label="Закрыть">×</button><p class="project3d-kicker">3D-ПРОЕКТИРОВАНИЕ</p><h2>Примеры 3D-проектов</h2><p class="project3d-intro">Планировка и визуализация пространства до начала ремонтных работ.</p><div class="project3d-grid">${projects3d.map((p,i)=>`<button type="button" class="project3d-card" data-i="${i}"><img src="${p[0]}" alt="3D-проект: ${p[1]}" loading="lazy"><span>${p[1]}</span></button>`).join('')}</div></div>`;document.body.appendChild(modal);
 const style=document.createElement('style');style.textContent=`.service-cards article.service-3d-featured{cursor:pointer;position:relative;padding-top:20px;border-color:rgba(241,201,121,.62);box-shadow:0 18px 48px rgba(0,0,0,.28),inset 0 0 0 1px rgba(241,201,121,.08);transition:transform .25s,border-color .25s}.service-cards article.service-3d-featured:hover{transform:translateY(-4px);border-color:#f1c979}.service3d-preview{position:relative;height:105px;margin:12px -10px 0;overflow:hidden;border:1px solid rgba(217,166,79,.3)}.service3d-preview img{width:100%;height:100%;object-fit:cover}.service3d-preview:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 35%,rgba(0,0,0,.82))}.service3d-preview span{position:absolute;z-index:1;left:10px;bottom:8px;color:#f1c979;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.service-3d-featured h3{margin-top:20px}.service3d-cta{display:flex!important;align-items:center;justify-content:center;min-height:42px;margin-top:16px!important;padding:0 12px;border:1px solid #d9a64f;background:linear-gradient(135deg,#f0c66e,#b97c32);color:#101010!important;font-weight:800!important;text-transform:uppercase;letter-spacing:.05em}.project3d-modal{position:fixed;inset:0;z-index:9998;display:none;overflow:auto;background:rgba(0,0,0,.94);padding:45px 20px}.project3d-modal.open{display:block}.project3d-panel{position:relative;width:min(1180px,100%);margin:auto;padding:42px;background:#061017;border:1px solid rgba(217,166,79,.35);box-shadow:0 25px 80px rgba(0,0,0,.5)}.project3d-close{position:absolute;right:18px;top:18px;width:46px;height:46px;border:1px solid rgba(217,166,79,.55);background:#02090e;color:#f1c979;font-size:28px;cursor:pointer}.project3d-kicker{margin:0 0 10px;color:#f1c979;font-size:10px;font-weight:700;letter-spacing:.2em}.project3d-panel h2{margin:0;font:400 46px Georgia,serif;color:#f7f3ea}.project3d-intro{color:#c4c6c5;font-size:13px;margin:14px 0 30px}.project3d-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.project3d-card{position:relative;padding:0;border:1px solid rgba(217,166,79,.28);background:#02090e;overflow:hidden;cursor:zoom-in;aspect-ratio:1/1;color:#fff}.project3d-card img{width:100%;height:100%;object-fit:cover;transition:transform .3s}.project3d-card:hover img{transform:scale(1.015)}.project3d-card span{position:absolute;left:0;right:0;bottom:0;padding:40px 18px 15px;text-align:left;background:linear-gradient(transparent,rgba(0,0,0,.9));font:400 22px Georgia,serif}@media(max-width:760px){.service3d-preview{height:150px;margin-top:10px}.project3d-modal{padding:0}.project3d-panel{min-height:100dvh;padding:70px 15px 25px;border:0}.project3d-panel h2{font-size:36px}.project3d-grid{grid-template-columns:1fr;gap:14px}.project3d-card{aspect-ratio:1/1}.project3d-close{position:fixed;z-index:2;right:12px;top:12px}}`;document.head.appendChild(style);
 function open3d(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open')}
 function close3d(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('lightbox-open')}
 link3d.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open3d()});service3d.addEventListener('click',open3d);service3d.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open3d()}});
 modal.querySelector('.project3d-close').addEventListener('click',close3d);modal.addEventListener('click',e=>{if(e.target===modal)close3d()});modal.querySelectorAll('.project3d-card').forEach((card,i)=>card.addEventListener('click',()=>{lightboxImage.src=projects3d[i][0];lightboxImage.alt='3D-проект: '+projects3d[i][1];lightboxName.textContent=projects3d[i][1]+' · 3D-проект';lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open')&&!lightbox.classList.contains('open'))close3d()});
}